defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: True
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment ⭐ 必须修改
env:
  num_envs: 512 # Number of drones for training - 根据GPU内存调整
  max_episode_length: 2200 # 最大episode长度 - 根据任务复杂度调整
  env_spacing: 8.0
  num_obstacles: 350 # 静态障碍物数量 - 根据地图大小调整

env_dyn:
  num_obstacles: 80 # 动态障碍物数量 - 设为0则无动态障碍物
  vel_range: [0.5, 1.5] # 动态障碍物速度范围 [min, max]
  local_range: [5.0, 5.0, 4.5] # 动态障碍物移动范围 [x, y, z]

viewer:
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: NavRL
  name: navigation_training
  entity: CERLAB-UAV-RL-Navigation
  mode: offline # online
  run_id: #kw9xf9k9
